In [17]:
import pandas as pd
import os
file_path = './data/raw'
csv_files = [
    "01_fund_master.csv",
    "02_nav_history.csv",
    "03_aum_by_fund_house.csv",
    "04_monthly_sip_inflows.csv",
    "05_category_inflows.csv",
    "06_industry_folio_count.csv",
    "07_scheme_performance.csv",
    "08_investor_transactions.csv",
    "09_portfolio_holdings.csv",
    "10_benchmark_indices.csv"
]

for file_name in csv_files:
    current_path = os.path.join(file_path, file_name)
    try:
        file_read = pd.read_csv(current_path)
        print(f"\n==========================================")
        print(f"📄 File name : {file_name}") 
        print(f"==========================================")
        print(f" Shape : {file_read.shape}")
        print(f" Dtypes :\n{file_read.dtypes}")
        print(f" Head (Top 2 Rows) :")
        display(file_read.head(2))

    except FileNotFoundError:
        print(f" File not found: {file_name}")

==========================================
📄 File name : 01_fund_master.csv
==========================================
 Shape : (40, 15)
 Dtypes :
amfi_code               int64
fund_house             object
scheme_name            object
category               object
sub_category           object
plan                   object
launch_date            object
benchmark              object
expense_ratio_pct     float64
exit_load_pct         float64
min_sip_amount          int64
min_lumpsum_amount      int64
fund_manager           object
risk_category          object
sebi_category_code     object
dtype: object
 Head (Top 2 Rows) :

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01

==========================================
📄 File name : 02_nav_history.csv
==========================================
 Shape : (46000, 3)
 Dtypes :
amfi_code      int64
date          object
nav          float64
dtype: object
 Head (Top 2 Rows) :

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474

==========================================
📄 File name : 03_aum_by_fund_house.csv
==========================================
 Shape : (90, 5)
 Dtypes :
date               object
fund_house         object
aum_lakh_crore    float64
aum_crore           int64
num_schemes         int64
dtype: object
 Head (Top 2 Rows) :

         date           fund_house  aum_lakh_crore  aum_crore  num_schemes
0  2022-03-31      SBI Mutual Fund            6.05     605000          186
1  2022-03-31  ICICI Prudential MF            4.65     465000          216

==========================================
📄 File name : 04_monthly_sip_inflows.csv
==========================================
 Shape : (48, 6)
 Dtypes :
month                         object
sip_inflow_crore               int64
active_sip_accounts_crore    float64
new_sip_accounts_lakh        float64
sip_aum_lakh_crore           float64
yoy_growth_pct               float64
dtype: object
 Head (Top 2 Rows) :

,month,sip_inflow_crore,active_sip_accounts_crore,new_sip_accounts_lakh,sip_aum_lakh_crore,yoy_growth_pct
0,2022-01,11517,4.91,9.1,4.80,NaN
1,2022-02,11438,4.93,8.2,4.85,NaN

==========================================
📄 File name : 05_category_inflows.csv
==========================================
 Shape : (144, 3)
 Dtypes :
month                object
category             object
net_inflow_crore    float64
dtype: object
 Head (Top 2 Rows) :

     month   category  net_inflow_crore
0  2024-04  Large Cap            2413.0
1  2024-04    Mid Cap            3897.0

==========================================
📄 File name : 06_industry_folio_count.csv
==========================================
 Shape : (21, 6)
 Dtypes :
month                   object
total_folios_crore     float64
equity_folios_crore    float64
debt_folios_crore      float64
hybrid_folios_crore    float64
others_folios_crore    float64
dtype: object
 Head (Top 2 Rows) :

,month,total_folios_crore,equity_folios_crore,debt_folios_crore,hybrid_folios_crore,others_folios_crore
0,2022-01,13.26,9.28,1.86,0.80,1.33
1,2022-04,13.91,9.74,1.95,0.83,1.39

==========================================
📄 File name : 07_scheme_performance.csv
==========================================
 Shape : (40, 19)
 Dtypes :
amfi_code               int64
scheme_name            object
fund_house             object
category               object
plan                   object
return_1yr_pct        float64
return_3yr_pct        float64
return_5yr_pct        float64
benchmark_3yr_pct     float64
alpha                 float64
beta                  float64
sharpe_ratio          float64
sortino_ratio         float64
std_dev_ann_pct       float64
max_drawdown_pct      float64
aum_crore               int64
expense_ratio_pct     float64
morningstar_rating      int64
risk_grade             object
dtype: object
 Head (Top 2 Rows) :

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate

==========================================
📄 File name : 08_investor_transactions.csv
==========================================
 Shape : (32778, 13)
 Dtypes :
investor_id            object
transaction_date       object
amfi_code               int64
transaction_type       object
amount_inr              int64
state                  object
city                   object
city_tier              object
age_group              object
gender                 object
annual_income_lakh    float64
payment_mode           object
kyc_status             object
dtype: object
 Head (Top 2 Rows) :

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified

==========================================
📄 File name : 09_portfolio_holdings.csv
==========================================
 Shape : (322, 8)
 Dtypes :
amfi_code              int64
stock_symbol          object
stock_name            object
sector                object
weight_pct           float64
market_value_cr      float64
current_price_inr    float64
portfolio_date        object
dtype: object
 Head (Top 2 Rows) :

,amfi_code,stock_symbol,stock_name,sector,weight_pct,market_value_cr,current_price_inr,portfolio_date
0,119551,POWERGRID,Power Grid Corporation,Utilities,13.85,737.09,6011.08,2025-12-31
1,119551,HDFCBANK,HDFC Bank Ltd,Banking,11.19,88.97,1074.65,2025-12-31

==========================================
📄 File name : 10_benchmark_indices.csv
==========================================
 Shape : (8050, 3)
 Dtypes :
date            object
index_name      object
close_value    float64
dtype: object
 Head (Top 2 Rows) :

         date index_name  close_value
0  2022-01-03    NIFTY50     17492.79
1  2022-01-04    NIFTY50     17689.64

dict_keys(['meta', 'data', 'status'])
{'date': '03-06-2026', 'nav': '194.08100'}

         date        nav
0  03-06-2026  194.08100
1  02-06-2026  193.12950